### ISSUE TITLE
can mysql_streamer be used to restore the database at a specified time

### ISSUE THREAD

**Issue by csrgxtu** [Yelp/mysql_streamer#9]
since mysql_streamer can capture every change on MySQL, and send the operations to Kafka, so it can be used to log all the operations and then can be used to restore the database at a specific timestamp based on the operations in Kafka.

**Comment by premsantosh** [comment]
You are essentially correct in saying that you can reconstruct the original table using the stream. This concept is known as [stream table duality](http://docs.confluent.io/2.1.0-alpha1/streams/concepts.html#duality-of-streams-and-tables). 
But, you will have to clarify what you mean by "restore the table at a specified time" because time here is relative. Are you talking about the time when the query was run on the table or the time when our data pipeline constructed the message for the query? The former can get more complicated to deal with if you have a hierarchical database topology with replication. In this case, we would also need to take into account the replication delay between master and the replica that the MySQLStreamer is connected to. So the timestamp at which the query was executed at master will be different from when its been executed at the replica.

**Comment by kdparker** [comment]
How this works also depends heavily on your Kafka cluster's cleanup policy. If you're using the default then you won't keep any messages published before the retention window, and if you're using compaction then you'll only keep the most recent messages for any given primary key. Basically, the default means that you only know of changes in a fairly limited timeframe, and compaction means you'd only really know the current state of the database.

This means that if you wanted this system to operate at any reasonable storage, you would still need to take some kind of snapshot of the entire database state at intervals that match roughly with your retention window. From that, you would be able to replay the events on that snapshot up to a given timestamp (which as noted will be off on account of the replication delay).

**Comment by kdparker** [comment]
Going to close this issue since there's nothing actionable here
